### ISSUE TITLE
Número real com vírgula entrega mensagem ruim

### ISSUE THREAD

**Issue by fpelz** [UNIVALI-LITE/Portugol-Nucleo#1]
construções como:  2,5 - 3,78 apresentam a mensagem padrão do erro MissignTokenException. Melhorar a mensagem para algo parecido com: "valores reais devem utilizar o caracter . como separador decimal".

**Comment by AdsonEsteves** [comment]
@noschang 
Considerando isso que você falou, não estaria correta a mensagem e portanto a issue resolvida?

**Comment by noschang** [comment]
@AdsonEsteves . Existem dois casos em que este erro pode ocorrer. Um é quando a expressão está na declaração de variáveis e outra é quando a expressão está no meio de outras expressões.

Por exemplo. Se a expressão estiver no meio de uma declaração de variável (```real f = 3,4```), o parser vai assumir que a construção intencional é ```real f = 3, <nome-da-variavel> = 4```. Neste caso ele exibe uma mensagem amigável informando que o nome da variável está faltando.

No entanto, quando a expressão está no meio de outras expressões (```a = 2 + 3,4 + 1```), o parser vai entender que a primeira parte da expressão está correta (```a = 2 + 3```), mas não vai saber o que fazer com a outra parte (```,4 + 1```).

Quando este segundo caso ocorre, o parser simplesmente joga um "MissingTokenException". Esta mensagem não é nem de longe auto explicativa. O usuário não vai ter a mínima idéia do que fazer para arrumar o código.

O ideal é substituir esta mensagem por uma mensagem do tipo: "Você está utilizando o caracter errado como separador decimal. Você utilizou o caracter ',', porém o correto é o caracter '.'"

**Comment by AlissonSteffens** [comment]
Isso é treta no próprio ANTLR, não tem muito o que fazer...

**Comment by rytix** [comment]
Não acontece mais o MissMatchToken, porém a mensagem de erro não faz sentido.
Como não acontece mais o MissMatch vou fechar esta Issue e colocar a mensagem de erro na Issue #112
