### ISSUE TITLE
Erro na geração de código JAVA

### ISSUE THREAD

**Issue by AlissonSteffens** [UNIVALI-LITE/Portugol-Nucleo#102]
No exemplo **Animação** das subrotinas,(https://github.com/UNIVALI-LITE/Portugol-Studio/issues/183) foi encontrado um erro de escape no código

```JAVA
escreva("\\ /\n");
```

Foi descoberto que o gerador de código gera a seguinte resposta:
```JAVA
escreva("\ /\n");
```

É necessário encontrar o momento onde isso acontece, e resolver este problema.

**Comment by AlissonSteffens** [comment]
@elieserdejesus , @noschang , alguém sabe dizer onde pode estar o problema???

**Comment by elieserdejesus** [comment]
@AlissonSteffens , acho que essa issue eu posso assumir.

**Comment by elieserdejesus** [comment]
@AlissonSteffens , não tenho o exemplo **Animação** dentro de subrotinas aqui. Dei um pull no repositório dos recursos e não veio nada. Tens certeza que este exemplo está no master?

**Comment by AdsonEsteves** [comment]
Não?
![image](https://cloud.githubusercontent.com/assets/8836540/26810760/da3e0728-4a43-11e7-890f-103e933e6df8.png)

**Comment by AdsonEsteves** [comment]
@elieserdejesus 

Se você estiver entrando na pasta do recursos, o exemplo estará com o nome de lagarta.por

**Comment by AlissonSteffens** [comment]
@elieserdejesus esse exemplo tá no Portugol a bastante tempo.
![tumblr_o4ww93mqzj1rb71hfo4_r1_500](https://cloud.githubusercontent.com/assets/6234230/26812271/24d5dc30-4a4d-11e7-85f1-2d5dbbea2706.gif)

**Comment by elieserdejesus** [comment]
@AlissonSteffens , podes assumir essa issue? Basta criar um novo teste em **GeradorCodigoUtilsTest** e modificar **Utils.preservaCaracteresEspeciais** para fazer mais um replace quando encontrar barras duplas.
