### ISSUE TITLE
Testes Quebrados

### ISSUE THREAD

**Issue by AlissonSteffens** [UNIVALI-LITE/Portugol-Nucleo#103]
Muitos testes do núcleo estão quebrados... Ou o núcleo está quebrado... Não sei mais nada
![6kxuukk](https://cloud.githubusercontent.com/assets/6234230/26808964/3584267e-4a37-11e7-9352-1b9260c21b21.gif)

**Comment by elieserdejesus** [comment]
testei aqui e deu um problema na geração de código java para o exemplo jogos/Arkanoid.por.  
```
Não foi possível compilar o programa, o código contém erros.
```

Esse exemplo é novo?

**Comment by AlissonSteffens** [comment]
Nem sei de onde ele veio, 😞

**Comment by AdsonEsteves** [comment]
Esse exemplo é do @noschang , ele nem foi terminado, muito menos adicionado, podem ignora-lo.

@elieserdejesus 
O Erro que o @AlissonSteffens fala, é nos arquivos do TestPackages dentro de execução>arquivos, que não passaram no teste.

![image](https://cloud.githubusercontent.com/assets/8836540/26810710/926245e0-4a43-11e7-91be-e1581da56464.png)

**Comment by elieserdejesus** [comment]
@AlissonSteffens e @AdsonEsteves , esses arquivos **.java** e **.por** dentro de **execucao/arquivos** não são testes, eles são apenas templates/resources usados pelos testes. Cada teste procura (baseado no seu nome) um arquivo .por, compila ele, procura um arquivo .java (o gabarito) e verifica se o código compilado é igual ao "gabarito" (.java). Esta pasta **execucao/arquivos** contém a entrada de cada testes (.por) e a saída esperada (.java). Estes arquivos não são testes. 

Estes são os testes:
![image](https://cloud.githubusercontent.com/assets/1012741/26824390/977b8f02-4a87-11e7-9bca-2a04346f730d.png)

**Comment by elieserdejesus** [comment]
![image](https://cloud.githubusercontent.com/assets/1012741/26826954/649224d4-4a91-11e7-867e-2e607fca51fb.png)

**Comment by AlissonSteffens** [comment]
Ok, obrigado @elieserdejesus
