### ISSUE TITLE
Pare as vezes vira sw_break quando não deveria

### ISSUE THREAD

**Issue by AlissonSteffens** [UNIVALI-LITE/Portugol-Nucleo#108]
No código Programe.por (https://github.com/UNIVALI-LITE/Portugol-Studio-Recursos/pull/1) o código
```
para(j=0; j<u.numero_elementos(numeros); j++)
		{
			//necessário para o desenho não começar com zeros na frente, o j terá a posição certa a se começar a desenhar
			se(numeros[j] != 0)
			{
				pare
			}
		}
```
vira 
```JAVA
for(j = 0; j < u_1496774493645.numero_elementos(numeros); j = j + 1)
    {
        if (this.interrupcaoSolicitada || Thread.currentThread().isInterrupted()) {throw new InterruptedException();}

        realizarParada(1157, 6);
        if(numeros[j] != 0)
        {
            realizarParada(1159, 4);
            ___sw_break___ = true;

        }


    }
```
e ocorre um erro pelo fato de a variável **sw_break** não ter sido inicializada.
Acho que neste caso deveria ser somente **break**

**Comment by elieserdejesus** [comment]
o @noschang manja desse **___sw_break___** 😄 . Pergunte a ele como resolver!

**Comment by AlissonSteffens** [comment]
@elieserdejesus , ele não manja não, to em recursão
![w6attrl](https://user-images.githubusercontent.com/6234230/26848301-51a46c2a-4ad6-11e7-8e94-e19bc610f044.gif)

**Comment by elieserdejesus** [comment]
eu acho que o @noschang botou esse sw_break pra resolver situações onde existe um escolha dentro de outro.

> e ocorre um erro pelo fato de a variável sw_break não ter sido inicializada.

E se inicializar? Se mudar o gerador de código para sempre inicializar essa variável como false?

**Comment by AlissonSteffens** [comment]
a questão é, deveria ter sido colocado só se tivesse em um **escolha caso**, mas tá vindo no **se** também

**Comment by elieserdejesus** [comment]
A classe GeradorSwitchCase tem um método que gera um seSenao (não me pergunte porque) 😄 

https://github.com/UNIVALI-LITE/Portugol-Nucleo/blob/d3d42dc4d17d93ca6f565f6305d675bdd6bdd7aa/src/br/univali/portugol/nucleo/execucao/gerador/helpers/GeradorSwitchCase.java#L71

**Comment by AlissonSteffens** [comment]
isso que não tá rolando, vou investigar...

**Comment by AlissonSteffens** [comment]
@elieserdejesus , antes de gerar o release do Núcleo, acho legal resolver este problema

**Comment by elieserdejesus** [comment]
concordo @AlissonSteffens , e a bola está com você 😄 !

**Comment by elieserdejesus** [comment]
@AlissonSteffens , corrigi essa issue, entretanto o exemplo novo ainda gera problema de compilação, mas são outros problemas e é melhor resolvê-los em outra issue.
