### ISSUE TITLE
Problema de perfomance da biblioteca Graficos no Linux

### ISSUE THREAD

**Issue by noschang** [UNIVALI-LITE/Portugol-Nucleo#109]
No Linux, se o usuário tentar desenhar alguma coisa na tela sem chamar a função ```Graficos.limpar()``` antes, o modo gráfico trava completamente, chegando a fazer o Portugol Studio parar de responder.

Ao adicionar a chamada para a função ```Graficos.limpar()```, o programa passa a executar sem travamento. Este comportamento não ocorre no Windows.

Neste caso, acredito que não podemos assumir que o usuário vá se preocupar com este detalhe. Na verdade a maioria dos usuários não chama esta função.

Portanto sugiro alterarmos a biblioteca Graficos para chamar automaticamente esta função antes de desenhar qualquer coisa. 

Basta adicionar este código ```graficos.fillRect(0, 0, larguraTela, alturaTela);``` [aqui](https://github.com/UNIVALI-LITE/Portugol-Nucleo/blob/master/src/br/univali/portugol/nucleo/bibliotecas/graficos/SuperficieDesenhoImpl.java#L87)

**Comment by elieserdejesus** [comment]
@noschang , não consegui reproduzir esse bug no meu Ubuntu (64 bits). Usei esse código para testar:
```
programa
{
	inclua biblioteca Graficos
	inclua biblioteca Teclado
	
	funcao inicio()
	{
		Graficos.iniciar_modo_grafico(verdadeiro)

		
		enquanto (nao Teclado.alguma_tecla_pressionada()) 
		{
			Graficos.definir_cor(Graficos.COR_VERMELHO)			
			Graficos.desenhar_retangulo(50, 50, 50, 50, verdadeiro, verdadeiro)

			Graficos.renderizar()
						
		}
		
	}
}
```

**Comment by noschang** [comment]
@elieserdejesus. Abra o exemplo do pong no teu PC. Ele deve travar toda a interface do Portugol Studio.

Teste também com este código aqui:

[Parallax.zip](https://github.com/UNIVALI-LITE/Portugol-Nucleo/files/1068313/Parallax.zip)
