### ISSUE TITLE
Mensagens de erro que não fazem sentido [Fixo]

### ISSUE THREAD

**Issue by rytix** [UNIVALI-LITE/Portugol-Nucleo#112]
Esta Issue conterá todas as mensagens de erro que não fazem sentido.

- [ ] Mensagem de erro nº 1
- [ ] Mensagem de erro nº 2

--- Mensagem de erro nº 1 ---
![image](https://user-images.githubusercontent.com/7809511/26991776-1e55fab0-4d32-11e7-8be3-64923992004f.png)
```
programa
{
   funcao inicio()  {
      inteiro a.
      escreva("teste")
   }
}
```
--- Mensagem de erro nº 2 ---
![image](https://user-images.githubusercontent.com/7809511/26991959-e260087e-4d32-11e7-9c84-aa0b367b3985.png)
```
programa
{
   funcao inicio()  {
      inteiro a = (2,5 - 3,78)
   }
}
```

**Comment by Rafaelfcosta** [comment]
This issue was moved to UNIVALI-LITE/Portugol-Studio#308
