### ISSUE TITLE
Será possivel retornar vetor e matriz??????

### ISSUE THREAD

**Issue by fpelz** [UNIVALI-LITE/Portugol-Nucleo#32]
Decidir se esse tipo de construção será possível na linguagem

**Comment by AlissonSteffens** [comment]
@elieserdejesus foi uma escolha do Raabe, e e não será. Ao menos com essa gramática não.

**Comment by noschang** [comment]
@elieserdejesus, o que o @AlissonSteffens disse está correto. No entanto, acho que após finalizado este release devemos sentar com o Raabe e a equipe e reavaliar algumas decisões tomadas.

Este é um recurso que pode ser bem útil na linguagem e talvez não atrapalhe tanto assim no aprendizado dos usuários. Outro recurso que vale ser reavaliado é a possibilidade de ter vetor e matriz com dimensões dinâmicas.
