### ISSUE TITLE
var. escreva (erro semantico não capturado)

### ISSUE THREAD

**Issue by fpelz** [UNIVALI-LITE/Portugol-Nucleo#47]
Ao executar a analise semântica no código a seguir é mostrado para o usuário o stacktrace,

<pre>
programa
{
   funcao inicio()  {
      inteiro a.
      escreva("teste")
   }
}
</pre>

**Comment by rytix** [comment]
Este erro foi corrigido, agora somente a mensagem de erro não faz sentido, será criado uma nova issue com casos que a mensagem de erro não faz sentido.
