### ISSUE TITLE
Parada extra no debug do laço para

### ISSUE THREAD

**Issue by fpelz** [UNIVALI-LITE/Portugol-Nucleo#48]
Ao realizar a depuração detalhada no laço para, é feito o highlight na condição antes de realizar o highlight na declaração, essa primeira parada não deveria acontecer.

**Comment by rytix** [comment]
O seguinte código rodou normalmente:
```
programa
{
	funcao inicio()
	{
		para(inteiro i = 0; i < 5; i++){
			escreva("Pastel")
		}
	}
}
```
@fpelz Acredito que a Issue esteja resolvida no atual master do Portugol, caso contrario acho que podes reabrir a Issue com mais informações.
