### ISSUE TITLE
Travamento após a correção de erro e execução

### ISSUE THREAD

**Issue by fpelz** [UNIVALI-LITE/Portugol-Nucleo#49]
Investigar travamento. Uma das suspeitas é o mecanismo threads utilizado para chamar as funções do núcleo dentro do Portugol Studio.

Um travamento constante possuí a seguinte característica: 

1 - O código possui erros, 
2 - Corrige-se os erros e rapidamente clique em play
3 - repita os passos com rapidez e algum momento a IDE travará;

outro cenário que chama atenção é:
1 - Códigos que possuem avisos do semântico. (sublinhado amarelo)

**Comment by rytix** [comment]
Não consegui reproduzir o bug na última versão do portugol studio e nem na versão em desenvolvimento.

O bug é de setembro de 2013, talvez ele já tenha sido corrigido.

**Comment by noschang** [comment]
OK! Se ocorrer novamente, reabrimos a issue!
