### ISSUE TITLE
Semântico não realiza checagem de tipos dentro do escreva

### ISSUE THREAD

**Issue by noschang** [UNIVALI-LITE/Portugol-Nucleo#52]
O semântico deixa utilizar funções com retorno vazio dentro do escreva.
Permite utilizar um escreva dentro do outro eu um leia dentro do escreva.
     
Ex.:
<pre>programa
{
     funcao inicio()
     {
          inteiro a

          escreva("Teste 1\n", escreva("Teste 2\n\n"), leia(a), bug(), "Teste 3" )
     }

     funcao bug()
     {

     }
}
</pre>

**Comment by rytix** [comment]
Resolvido no pull request #64
