### ISSUE TITLE
Não acontece erro sintático em construção senao seguido de expressão e o interpretador executa o bloco senao quando a expressão do se é verdadeira

### ISSUE THREAD

**Issue by fpelz** [UNIVALI-LITE/Portugol-Nucleo#53]
programa
{
    funcao inicio()
    {
        inteiro a 
        leia (a)
        se (a > 0)
            escreva("teste")
        senao (a == 0) 
            escreva ("deveria dar erro")

```
}
```

}

**Comment by rytix** [comment]
Este Bug não acontece mais na nova versão:
![image](https://user-images.githubusercontent.com/7809511/26990977-0ef1dc2c-4d2f-11e7-8481-5d79d892d744.png)
Então acredito que ele esta resolvido
![image](https://zippy.gfycat.com/ExaltedPastelAsiaticgreaterfreshwaterclam.gif)
