### ISSUE TITLE
Função "leia" está lendo coisas indevidas

### ISSUE THREAD

**Issue by noschang** [UNIVALI-LITE/Portugol-Nucleo#56]
É possível passar algumas coisas bem bizarras como parâmetro para o "leia".

![erro_lendo_coisas_indevidas](https://cloud.githubusercontent.com/assets/709553/13150075/4ddfb5b4-d64b-11e5-86c4-c824ad067607.png)

Algoritmo para testes:
[erro_lendo_coisas_indevidas.por.zip](https://github.com/UNIVALI-LITE/Portugol-Nucleo/files/136525/erro_lendo_coisas_indevidas.por.zip)

------
Ao testar o seguinte código:
http://pastebin.com/gYmyeSeV

O seguinte erro é apresentado pelo compilador:
![image](https://cloud.githubusercontent.com/assets/7809511/13060204/f09a387e-d416-11e5-8ae3-1402ac26d472.png)

Porém ao deixar o valor da variável n como constante declarando seu valor no inicio, e logo após tentando ler ela (**alterando a constante**) o compilador permite a alteração da constante e o uso do valor lido na matriz.
Código:
http://pastebin.com/xA0ySEFC

Resultado:
![image](https://cloud.githubusercontent.com/assets/7809511/13060288/6ebde2b4-d417-11e5-866d-694f5b49f668.png)

Além disto quando se tenta deixar a variavel n sem valor algum na hora de inicializar:
Código:
http://pastebin.com/EdxwADMG

Uma exceção do java é jogada no console para o usuário:
![image](https://cloud.githubusercontent.com/assets/7809511/13060335/c759dd42-d417-11e5-981f-c15e661cd8c9.png)

**Comment by rytix** [comment]
Coisas bizarras no leia corrigidas no pull request #63
