### ISSUE TITLE
NullPointer no motor de áudio

### ISSUE THREAD

**Issue by noschang** [UNIVALI-LITE/Portugol-Nucleo#61]
@elieserdejesus, no meu Linux, o exemplo da bateria dá um erro que parece ser um NullPointer aleatoriamente.

![bug1](https://cloud.githubusercontent.com/assets/709553/13439688/6b785c1c-dfcd-11e5-8e47-bc1ab9f68179.png)

Eu rodo o exemplo várias vezes e em algumas execuções o problema ocorre, em outras não.

**Comment by elieserdejesus** [comment]
@noschang , teu linux é Ubuntu ou Mint?

**Comment by noschang** [comment]
O meu é Mint, mas o Mint é baseado no Ubuntu, só muda a interface gráfica (pelo que eu sei).

**Comment by noschang** [comment]
Corrigido no Pull Request #62.
