### ISSUE TITLE
Bug de funções e variáveis globais com o mesmo nome.

### ISSUE THREAD

**Issue by rytix** [UNIVALI-LITE/Portugol-Nucleo#67]
![image](https://cloud.githubusercontent.com/assets/7809511/13650327/e34b0308-e620-11e5-9fe4-9938142d8699.png)

**Comment by elieserdejesus** [comment]
![portugol](https://user-images.githubusercontent.com/1012741/29316342-07e32a5a-819e-11e7-9e77-59f6b732d1eb.gif)
