### ISSUE TITLE
Converter do ANTLR3 para o ANTLR4

### ISSUE THREAD

**Issue by rytix** [UNIVALI-LITE/Portugol-Nucleo#72]
Alguns bugs relatados, envolvem mexer no léxico do Portugol.
Como dar manutenção em um código ANTLR3 é relativamente complexo por possuir código java junto com a gramática, o código de gramática será convertido do ANTLR3 para o ANTLR4 a fim de separar o código java da gramatica e melhorar a manutenibilidade do sintático do núcleo.

**Comment by rytix** [comment]
![image](https://user-images.githubusercontent.com/7809511/26947824-6c32a2ba-4c6a-11e7-821b-6e859de68ea0.png)

**Comment by Rafaelfcosta** [comment]
This issue was moved to UNIVALI-LITE/Portugol-Studio#314
