### ISSUE TITLE
Remover uma parte do parenteses na função tela cheia cria estados inconsistentes no Portugol

### ISSUE THREAD

**Issue by rytix** [UNIVALI-LITE/Portugol-Nucleo#84]
No windows 7 a tela começa a piscar, no windows 10 ela reduz de tamanho, isso pode ter efeitos diferentes em diversos tipos de sistema operacional

![image](https://cloud.githubusercontent.com/assets/7809511/23230738/dfb78862-f923-11e6-9371-7cf5b9d2fde7.png)

![screenshot_1](https://cloud.githubusercontent.com/assets/7809511/23230960/aa518e2e-f924-11e6-921f-f7b62c572913.png)

**Comment by rytix** [comment]
@AlissonSteffens isso ainda está acontecendo ? fiz um teste aqui e parece estar tudo bem...

**Comment by AlissonSteffens** [comment]
Acho que não acontece mais, @AdsonEsteves pode confirmar??

**Comment by Rafaelfcosta** [comment]
This issue was moved to UNIVALI-LITE/Portugol-Studio#313
