### ISSUE TITLE
Coisas fora da Thread do Swing

### ISSUE THREAD

**Issue by noschang** [UNIVALI-LITE/Portugol-Nucleo#85]
A função entrar_modo_tela_cheia() da biblioteca Graficos está mexendo na janela fora da Thread do Swing. No linux deu tretas.

Esta função deve ser corrigida e as outras funções devem ser investigadas também.

**Comment by AlissonSteffens** [comment]
@noschang, acho que já foi corrigido, confere???

**Comment by noschang** [comment]
@elieserdejesus, pelo que me lembro corrigi isso sim. Pelo menos não está acusando nenhuma violação no nosso DEGIGRA (DEtector de Gambiarras na Interface GRAfica).

**Comment by elieserdejesus** [comment]
@noschang , esses dias acordei assustado as 03:30. Eu tinha sonhado (era um pesadelo) que usar um DEGIGRA o tempo todo estaria diminuindo a performance da renderização no PS, já que toda operação de pintura passa por um teste. Seria legal desativar o DEGIGRA e ver se aumenta alguma coisa no FPS de algum exemplo que tenha um FPS estável e fácil de comparar.

**Comment by AlissonSteffens** [comment]
![2f37d2ac81801ac0f083e2e83137e32f427828e7_hq](https://cloud.githubusercontent.com/assets/6234230/26833615/5b4dd36a-4aa9-11e7-8dbf-01f6828bf7e2.gif)

**Comment by rytix** [comment]
Acho que esta Issue estava ligada a Issue #84 
Caso Esta Issue esteja OK pode fechar as duas :P

**Comment by AlissonSteffens** [comment]
Foram removidas Coisas fora da Thread do Swing, fechando a Issue
