### ISSUE TITLE
Versão estável

### ISSUE THREAD

**Issue by peresbruno** [UNIVALI-LITE/Portugol-Nucleo#86]
Existem algumas tags no repositório (2.0, v2.5, etc.). Acredito que a tag v2.5 seja a versão estável mais atual, estou correto? Seria bacana indicar isso no README.

**Comment by AlissonSteffens** [comment]
Exato, a versão estável é a do release :smile: , mas irei adicionar esta informação no README sim :+1:

**Comment by AlissonSteffens** [comment]
O README do núcleo foi atualizado, a manda para o Studio, adicionarei esses dados lá (https://github.com/UNIVALI-LITE/Portugol-Studio/issues/224).
