### ISSUE TITLE
Problema no Sintático envolvendo o Realizar parada

### ISSUE THREAD

**Issue by rytix** [UNIVALI-LITE/Portugol-Nucleo#98]
Como o PS aceita pare depois de retorno quando o java compila o mundo explode.

![image](https://cloud.githubusercontent.com/assets/7809511/26802939/ccd71924-4a18-11e7-8f82-88c26ac4c453.png)

**Comment by noschang** [comment]
@elieserdejesus, @AdsonEsteves e @AlissonSteffens. Apenas explicando um pouco melhor o que o @rytix quis dizer.

Se olharem na imagem, vão ver que tem o código Portugol e um código Java em comentários. Este código Java é supostamente o código que o gerador do @elieserdejesus vai gerar para a função ```x```.

O problema é que para o depurador funcionar, o gerador de código "injeta" uma chamada para o método ```realizarParada``` antes e depois de cada instrução do código. O que supostamente está ocorrendo é que está sendo gerada uma chamada para o ```realizarParada``` após o ```return``` da função. Neste caso, o Java reclama porque esta chamada nunca será executada por causa do ```return```.

Como eu disse, estamos apenas supondo isso porque não chegamos a ver de fato o código Java que foi gerado, mas pelo Stacktrace do console, acreditamos que seja isso mesmo.

@elieserdejesus, o filho é teu...

**Comment by AlissonSteffens** [comment]
@noschang vou verificar isso hoje a tarde

**Comment by elieserdejesus** [comment]
> @elieserdejesus, o filho é teu...

![image](https://user-images.githubusercontent.com/1012741/26838193-cf0ccfb6-4ab5-11e7-97f9-0b51ce68ef0b.png)

**Comment by elieserdejesus** [comment]
people, please testem o PR https://github.com/UNIVALI-LITE/Portugol-Nucleo/pull/104

Quando um NoRetorne é encontrado nenhum código é gerado. No Java não pode ter nada depois de um return, caso contrario temos um erro de compilação.

**Comment by elieserdejesus** [comment]
decidimos corrigir isso no nível do sintático, detalhes em https://github.com/UNIVALI-LITE/Portugol-Nucleo/pull/104
